---
title: "R Notebook"
output: html_notebook
---
##loading the data and packages
```{r}
library(tidyverse)
library(janitor)

neighbourhood_rating <- read_csv("../raw_data/neighbourhood_rating.csv") %>% 
  clean_names()
green_spaces <- read_csv("../raw_data/green_spaces.csv") %>% 
  clean_names()
community_belonging <-read_csv("../raw_data/community_belonging.csv") %>% 
  clean_names()
```
```{r}
neighbourhood_rating
green_spaces
community_belonging
```
```{r}
neighbourhood_rating %>% 
  count(household_type)
```

```{r}
neighbourhood_rating %>% 
  count(date_code)
```
```{r}
neighbourhood_rating %>% 
  count(walking_distance_to_nearest_greenspace)
```
```{r}
neighbourhood_rating %>% 
  count(type_of_tenure)
```


```{r}
neighbourhood_rating %>% 
  count(type_of_tenure)
```
```{r}
neighbourhood_rating %>% 
  count(measurement)
```
```{r}
neighbourhood_rating %>% 
  count(units)
```

```{r}
neighbourhood_rating %>% 
  count(simd_quintiles)
```


```{r}
community %>% 
  count(measurement)

neighbourhood %>% 
  count(measurement)

neighbourhood %>% 
  count(feature_code
)

neighbourhood %>% 
  count(units)

neighbourhood %>% 
  count(value)

neighbourhood %>% 
  count(neighbourhood_rating)

neighbourhood %>% 
  count(simd_quintiles)
```

```{r}
green_spaces %>% 
  count(date_code)

green_spaces %>% 
  count(measurement)

green_spaces %>% 
  count(distance_to_nearest_green_or_blue_space)
```


```{r}
green_spaces
```

```{r}
green_spaces %>% 
  count(distance_to_nearest_green_or_blue_space)
```

```{r}
green_spaces %>% 
  count(age)
```

```{r}
green_spaces %>% 
  count(gender)
```

```{r}
green_spaces %>% 
  count(urban_rural_classification)
```

```{r}
green_spaces %>% 
  count(simd_quintiles)
```

```{r}
community_belonging
```

```{r}
community_belonging %>% 
  count(community_belonging)
```
```{r}
community_belonging %>% 
  count(feature_code)
```

```{r}
#council areas codes 
council_areas <- read_csv("../raw_data/967937c4-8d67-4f39-974f-fd58c4acfda5.csv") %>% 
  clean_names()

```

```{r}
council_areas<- council_areas %>% 
  select(ca, ca_name)
```
```{r}
council_areas %>% 
  rename(feature_code = ca)
```

```{r}
green_spaces_joined <- inner_join(
  green_spaces, council_areas, by = c("feature_code" = "ca"))
green_spaces_joined
```

```{r}

```

```{r}
council_areas
```
```{r}
green_spaces
```

```{r}
green_spaces_joined
```

```{r}
community_belonging_joined <- inner_join(
  community_belonging, council_areas, by = c("feature_code" = "ca")) 
community_belonging_joined
```
```{r}
neighbourhood_rating_joined <-  inner_join(
  neighbourhood_rating, council_areas, by = c("feature_code" = "ca"))
neighbourhood_rating_joined
```
```{r}
neighbourhood_rating_joined %>% 
  count(walking_distance_to_nearest_greenspace)
```

```{r}
neighbourhood_rating_joined %>% 
  filter(walking_distance_to_nearest_greenspace == "Less than 10 minutes") %>% 
  count(value)
```

```{r}
neighbourhood_rating_joined %>% 
  filter(walking_distance_to_nearest_greenspace == "More than 10 minutes") %>% 
  count(value)
```

```{r}
neighbourhood_rating_joined %>% 
  filter(walking_distance_to_nearest_greenspace == "Less than 10 minutes") %>% 
  count(neighbourhood_rating)
```

```{r}
neighbourhood_rating_joined %>% 
  filter(walking_distance_to_nearest_greenspace == "More than 10 minutes") %>% 
  count(neighbourhood_rating)
```

```{r}
#apparently south Lankarshire is ca where people have both access to a green space in more or less than 10 mins. This probably because the sample generally containts more values for South Lankarshire. Perhaps I can do a proportion?  
#Per capita = Unit / Number of people in a population
neighbourhood_rating_joined %>% 
  filter(walking_distance_to_nearest_greenspace == "Less than 10 minutes") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```

```{r}
#apparently south Lankarshire is ca where people have both access to a green space in more or less than 10 mins. This probably because the sample generally containts more values for South Lankarshire. Perhaps I can do a proportion?  
#Per capita = Unit / Number of people in a population
neighbourhood_rating_joined %>% 
  filter(walking_distance_to_nearest_greenspace == "More than 10 minutes") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```

```{r}
neighbourhood_rating_joined %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```

```{r}
neighbourhood_rating_joined %>% 
  filter(date_code == "2019",
    walking_distance_to_nearest_greenspace == "Less than 10 minutes") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```
```{r}
neighbourhood_rating_joined %>% 
  filter(date_code == "2019",
    walking_distance_to_nearest_greenspace == "More than 10 minutes") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```

```{r}
neighbourhood_rating_joined %>% 
  filter(date_code == "2019") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```
```{r}
neighbourhood_rating_joined %>% 
  filter(date_code == "2018") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```
```{r}
neighbourhood_rating_joined %>% 
  count(date_code)
```

```{r}
neighbourhood_rating_joined %>% 
  filter(date_code == "2017") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```

```{r}
neighbourhood_rating_joined %>% 
  filter(date_code == "2016") %>% 
  count(ca_name) %>% 
  arrange(desc(n))
```



```{r}
neighbourhood_rating %>% 
  count(urban_rural_classification)
```

```{r}
neighbourhood_rating_joined %>% 
  count(urban_rural_classification)
```
```{r}
green_spaces_joined %>% 
  count(distance_to_nearest_green_or_blue_space)
```

```{r}
green_spaces_joined %>% 
  count(gender)
```

##Are there certain groups that have/ lack local access to green space?


```{r}
green_spaces_joined
```

```{r}
green_spaces_joined %>% 
  count(distance_to_nearest_green_or_blue_space)
```

```{r}
#male/female access
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "A 5 minute walk or less") %>% 
  count(gender)
```
```{r}
#male/female access
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "An 11 minute walk or more") %>% 
  count(gender)
```
```{r}
#male/female access
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "Within a 6-10 minute walk") %>% 
  count(gender)
```

```{r}
#age access
green_spaces_joined %>% 
  count(age)
```

```{r}
#age access
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "A 5 minute walk or less",
         date_code == "2018") %>% 
  count(age)
```

```{r}
#age access
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "An 11 minute walk or more") %>% 
  count(age)
```
```{r}
green_spaces_joined
```

```{r}
#simd_quintiles
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "A 5 minute walk or less", 
         date_code == "2013") %>% 
  count(simd_quintiles)
```
```{r}
#simd_quintiles
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "An 11 minute walk or more") %>% 
  count(simd_quintiles)
```

```{r}
green_spaces_joined
```
```{r}
#simd_quintiles
green_spaces_joined %>% 
  filter(distance_to_nearest_green_or_blue_space == "A 5 minute walk or less", 
         date_code == "2019") %>% 
  count(simd_quintiles)
```


```{r}
#simd_quintiles
green_spaces_joined %>% 
  group_by(date_code) %>% 
  filter(distance_to_nearest_green_or_blue_space == "A 5 minute walk or less")

green_spaces_joined %>% 
ggplot(aes(x = simd_quintiles, colour = simd_quintiles))+
  geom_bar()
```



```{r}
green_spaces_joined %>% 
ggplot(aes(x = distance_to_nearest_green_or_blue_space, fill = simd_quintiles))+
  geom_bar()+
  facet_wrap(~date_code)
```

